version: 0.2

phases:
  install:
    commands:
      - echo Enterd the install phase
      - apt-get update -y
      - npm install claudia -g
      - aws --version
  pre_build:
    commands:
      - echo Enterd the pre_build phase
      - cd ./bot && npm install 
      - python -V
  build:
    commands:
      - echo Enterd build phase
      - claudia update
  post_build:
    commands:
      - echo Enterd post_build phase

